# This file is apparently from
# https://github.com/actions/starter-workflows/blob/f90b59f7cd6c78cb77ba8274dd8b01499074948b/ci/c-cpp.yml

# I had some help with this YML file from...
# - https://docs.github.com/en/actions/writing-workflows/quickstart#creating-your-first-workflow
# - https://docs.github.com/en/actions/writing-workflows/choosing-when-your-workflow-runs/triggering-a-workflow#using-multiple-events
# - https://docs.github.com/en/actions/writing-workflows/workflow-syntax-for-github-actions#using-multiple-events
# - https://docs.github.com/en/actions/writing-workflows/workflow-syntax-for-github-actions#using-a-single-event
# - https://docs.github.com/en/actions/writing-workflows/choosing-when-your-workflow-runs/triggering-a-workflow#using-a-single-event
# - https://docs.github.com/en/actions/writing-workflows/choosing-when-your-workflow-runs/events-that-trigger-workflows#push
# - https://docs.github.com/en/actions/writing-workflows/choosing-when-your-workflow-runs/events-that-trigger-workflows#pull_request

name: C/C++ CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: make
      run: make
    - name: make clean
      run: make clean
